[TH2-3096] Migrated to codec 4.5.0-dev
th2-net/th2-codec-qfj pull request #2
Opened 2022-02-02 21:21 UTC by Nikita-Smirnov-Exactpro

2022-02-03 07:41 UTC, ivandruzhinin requested changes

2022-02-03 07:41 UTC, ivandruzhinin commented on build.gradle
> +    annotationProcessor 'com.google.auto.service:auto-service:1.0.1'
Please also remove `com.github.harbby.gradle.serviceloader` plugin

2022-02-03 07:41 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/codec/qfj/QFJCodec.java
> +@AutoService(IPipelineCodec.class)
Redundant - we only we need factory to be discoverable

2022-02-03 07:41 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/codec/qfj/QFJCodecSettings.java
> +@AutoService(IPipelineCodecSettings.class)
Redundant - we only we need factory to be discoverable

2022-02-10 13:56 UTC, Dmitriy-Yugay approved these changes

2022-04-08 09:38 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/codec/qfj/QFJCodec.java
> +    private Field<?> getField(int tag, String valueName, DataDictionary dataDictionary) {
Could you please extract converter to a separate class

2022-08-04 12:08 UTC, ivandruzhinin approved these changes

2022-08-04 12:15 UTC, merged